name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: |
        cd src
        npm install

    - name: Start application in background
      run: |
        cd src
        npm run start-bg
        sleep 10  # Wait for app to start

    - name: Run tests
      run: |
        cd src
        npm test

    - name: Deploy to EC2 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/nodejs_demoapp
          git pull
          cd src
          npm install
          pm2 restart all